name: hgkcb
description: Course table for hnit

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.0.0+1
  sqflite: ^1.1.6
  dio: ^2.1.13
  cookie_jar: ^1.0.0
  http: ^0.12.0+2
  html: ^0.14.0+2
  fluttertoast: ^3.1.0
  event_bus: ^1.1.0
  flutter_daydart: ^0.0.3
  shared_preferences: ^0.5.3+4
  numberpicker: ^1.1.0
  flutter_screenutil: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
